map_type: costmap #Map type to use, "voxel" or "costmap".

obstacle_range: 0.5 #The maximum range in meters at which to insert obstacles into the costmap using sensor data.
raytrace_range: 0.5 #The maximum range in meters at which to raytrace out obstacles from the map using sensor data. 
#The footprint of the robot specified in the robot_base_frame coordinate frame as a list in the format: [ [x1, y1], [x2, y2], ...., [xn, yn] ]. The footprint specification assumes the center point of the robot is at (0.0, 0.0) 
footprint: [[-0.40,-0.32],[-0.40,0.32], [0.50, 0.32], [0.50,-0.32]]
inflation_radius:

resolution: 0.05 #The resolution of the map in meters/cell. 
cost_scaling_factor: 10.0 #A scaling factor to apply to cost values during inflation. 


#observation_source: A list of observation source names separated by spaces
#	/sensor_frame: The frame of the origin of the sensor
#	/topic		 : The topic on which sensor data comes in for this source.
#	data_type    : The data type associated with the topic.
#	clearing     : Whether or not this observation should be used to clear out freespace
#	marking      : Whether or not this observation should be used to mark obstacles.

observation_sources: scan
scan: {sensor_frame: /laser, topic: /scan, data_type: LaserScan, clearing: true, marking: true}


#More information at http://wiki.ros.org/costmap_2d and http://wiki.ros.org/costmap_2d/flat 
