footprint: [[-0.40,-0.40],[-0.40,0.40], [0.50, 0.40], [0.50,-0.40]]
footprint_inflation: 0.5
obstacle_layer1:
  enabled: true
  combination_method: 1
  track_unknown_space: true    # true needed for disabling global path planning through unknown space
  obstacle_range: 2
  raytrace_range: 2.0
  observation_sources: scan #sonar
  scan: {sensor_frame: /laser, topic: /scan, data_type: LaserScan, clearing: true, marking: true}
#sonar: {topic: rosaria/sonar_pointcloud2, data_type: PointCloud2, clearing: true, marking: true}
  max_obstacle_height: 0.6
  min_obstacle_height: 0.0

obstacle_layer2:
  enabled: true
  combination_method: 1
  track_unknown_space: true    # true needed for disabling global path planning through unknown space
  obstacle_range: 2.0
  raytrace_range: 2.0
  observation_sources: sonar
#scan: {sensor_frame: /laser, topic: /scan, data_type: LaserScan, clearing: true, marking: true}
  sonar: {sensor_frame: /sonar,topic: /sonar, data_type: PointCloud, clearing: true, marking: true}
  max_obstacle_height: 0.6
  min_obstacle_height: 0.0

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  2.5  # exponential rate at which the obstacle cost drops off (default:10)
  inflation_radius:     0.2  # max. distance from an obstacle at which costs are incurred for planning paths.


static_layer:
  enabled:              true
