global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 2.5
   publish_frequency: 2.0
   static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: voxel
   plugins:

    - {name: static_layer,    type: "costmap_2d::StaticLayer"}

    - {name: obstacle_layer1,  type: "costmap_2d::ObstacleLayer"}
    
    - {name: obstacle_layer2,  type: "costmap_2d::ObstacleLayer"}

    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
